### ISSUE TITLE
NaNs in predictions

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/Nimbus-Inference#14]
### Report

When running the model on square images, @peterjchou was getting an error where all of the predictions across all the cells were NaNs. 

Peter, could you attach the image you used that generated the issue so we can investigate? Or if it's quite large, maybe a small crop of it, if you see the same issue there?

Thanks!

**Comment by peterjchou** [comment]
Thanks for starting this thread, Noah! I'm attaching the aSMA image and whole cell segmentation from fov1 that produced the attached cell_table. These are 8bit CODEX images.
[nimbus.zip](https://github.com/user-attachments/files/15844204/nimbus.zip)
<img width="323" alt="cell_table_screenshot" src="https://github.com/angelolab/Nimbus-Inference/assets/172431869/29afba57-e7ce-4ae8-b167-94680a64101d">

**Comment by JLrumberger** [comment]
Hi @peterjchou ,

I ran inference on the FoV you provided and don't get NaNs. My guess is that something is wrong with the normalization. Could you send me the `normalization_dict.json` in the `nimbus_output` folder?

Best,
Lorenz

**Comment by peterjchou** [comment]
Thanks for looking into this Lorenz, I appreciate the help! 

When you ran inference on the FoV did you also get visible predictions? I just ran it using only this FoV and didn't get NaNs this time, but the predictions were artifacts. 

[normalization_dict.json](https://github.com/user-attachments/files/15959301/normalization_dict.json)
<img width="1537" alt="nimbus_viewer_output" src="https://github.com/angelolab/Nimbus-Inference/assets/172431869/b95284f3-8937-44c0-b50f-3902e118a7c6">

**Comment by JLrumberger** [comment]
Your normalization_dict.json looks alright, but the predictions does not look correct. Here's my output:
![image](https://github.com/angelolab/Nimbus-Inference/assets/22618181/7714fa88-039b-4887-867e-b2cb64089f96)

I'll push some fixes to the main branch. Could you pull the main branch and re-run the notebook?

**Comment by peterjchou** [comment]
Hi Lorenz,

I reinstalled from the main branch and reran the notebook. Both with the FOV we've been discussing, as well as your example images. Both resulted in issues
<img width="1332" alt="fov1_singlefov" src="https://github.com/angelolab/Nimbus-Inference/assets/172431869/8a6eea95-b4bc-4ac1-b3e8-142b277c09c6">
<img width="1336" alt="fov4_exampledata" src="https://github.com/angelolab/Nimbus-Inference/assets/172431869/e2ddbacd-0e34-4000-a980-271606d9a0d7">

Happy to jump on a call, too - you can email me at peter.chou@enablemedicine.com

**Comment by JLrumberger** [comment]
Closed due to inactivity. Feel free to re-open if my assistance is still needed.
