### ISSUE TITLE
32bit images for cell segmentation as label mask

### ISSUE THREAD

**Issue by RouvenHoefflin** [angelolab/Nimbus-Inference#18]
### Report

Hi Nimbus-Team,

thanks for that amazing tool! 
I encounter an issue when working with large images containing > 65k cells. The cell segmentation image (labelled image) in these cases have to be 32bit (instead of 16bit), such that every cell gets its unique value.  However it seems like Nimbus does not support 32bit tiffs as segmentation images. Nimbus is running otherwise smoothly. When providing a 32bit instead of a 16bit tiffs as segmentation images I get this error while running  nimbus.predict_fovs():

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[37], line 1
----> 1 cell_table = nimbus.predict_fovs()
 
File F:\tmp\Nimbus-Inference\src\nimbus_inference\nimbus.py:191, in Nimbus.predict_fovs(self)
    189 print("Predictions will be saved in {}".format(self.output_dir))
    190 print("Iterating through fovs will take a while...")
--> 191 self.cell_table = predict_fovs(
    192     nimbus=self, dataset=self.dataset, output_dir=self.output_dir,
    193     normalization_dict=self.normalization_dict, save_predictions=self.save_predictions,
    194     half_resolution=self.half_resolution, batch_size=self.batch_size,
    195     test_time_augmentation=self.test_time_aug, suffix=self.dataset.suffix,
    196 )
    197 self.cell_table.to_csv(os.path.join(self.output_dir, "nimbus_cell_table.csv"), index=False)
    198 return self.cell_table
 
File F:\tmp\Nimbus-Inference\src\nimbus_inference\utils.py:394, in predict_fovs(nimbus, dataset, normalization_dict, output_dir, suffix, save_predictions, half_resolution, batch_size, test_time_augmentation)
    392 if half_resolution:
    393     prediction = cv2.resize(prediction, (w, h), interpolation=cv2.INTER_NEAREST)
--> 394 df = pd.DataFrame(segment_mean(instance_mask, prediction))
    395 if df_fov.empty:
    396     df_fov["label"] = df["label"]
 
File F:\tmp\Nimbus-Inference\src\nimbus_inference\utils.py:279, in segment_mean(instance_mask, prediction)
    270 def segment_mean(instance_mask, prediction):
    271     """Calculates the mean prediction per instance
    272     Args:
    273         instance_mask (np.array): instance mask
   (...)
    277         mean_per_cell (np.array): mean prediction per instance
    278     """
--> 279     props_df = regionprops_table(
    280         label_image=instance_mask, intensity_image=prediction,
    281         properties=['label' , 'centroid', 'intensity_mean']
    282     )
    283     return props_df
 
File C:\ProgramData\Anaconda3\envs\Nimbus\lib\site-packages\skimage\measure\_regionprops.py:974, in regionprops_table(label_image, intensity_image, properties, cache, separator, extra_properties)
    838 def regionprops_table(label_image, intensity_image=None,
    839                       properties=('label', 'bbox'),
    840                       *,
    841                       cache=True, separator='-', extra_properties=None):
    842     """Compute image properties and return them as a pandas-compatible table.
    843 
    844     The table is a dictionary mapping column names to value arrays. See Notes
   (...)
    972 
    973     """
--> 974     regions = regionprops(label_image, intensity_image=intensity_image,
    975                           cache=cache, extra_properties=extra_properties)
    976     if extra_properties is not None:
    977         properties = (
    978             list(properties) + [prop.__name__ for prop in extra_properties]
    979         )
 
File C:\ProgramData\Anaconda3\envs\Nimbus\lib\site-packages\skimage\measure\_regionprops.py:1262, in regionprops(label_image, intensity_image, cache, coordinates, extra_properties)
   1255         raise TypeError(
   1256                 'Non-integer image types are ambiguous: '
   1257                 'use skimage.measure.label to label the connected'
   1258                 'components of label_image,'
   1259                 'or label_image.astype(np.uint8) to interpret'
   1260                 'the True values as a single label.')
   1261     else:
-> 1262         raise TypeError(
   1263                 'Non-integer label_image types are ambiguous')
   1265 if coordinates is not None:
   1266     if coordinates == 'rc':
 
TypeError: Non-integer label_image types are ambiguous

### Version information

-----
alpineer            NA
ark                 NA
nimbus_inference    0.0.1
pandas              2.2.2
session_info        1.0.0
-----
Cython                      3.0.10
PIL                         9.5.0
aiohappyeyeballs            2.3.2
aiohttp                     3.10.0
aiosignal                   1.3.1
anyio                       NA
arrow                       1.3.0
asciitree                   NA
asttokens                   NA
async_timeout               4.0.3
attr                        23.2.0
attrs                       23.2.0
babel                       2.15.0
certifi                     2024.07.04
cffi                        1.16.0
charset_normalizer          2.1.1
colorama                    0.4.6
comm                        0.2.2
cv2                         4.10.0
cycler                      0.12.1
cython                      3.0.10
cython_runtime              NA
datasets                    2.20.0
dateutil                    2.9.0.post0
debugpy                     1.8.2
decorator                   5.1.1
defusedxml                  0.7.1
dill                        0.3.8
entrypoints                 0.4
exceptiongroup              1.2.2
executing                   2.0.1
fastjsonschema              NA
filelock                    3.15.4
fqdn                        NA
frozenlist                  1.4.1
fsspec                      2024.5.0
huggingface_hub             0.24.5
idna                        3.7
imagecodecs                 2024.6.1
imageio                     2.34.2
ipykernel                   6.29.5
ipython_genutils            0.2.0
ipywidgets                  8.1.3
isoduration                 NA
jedi                        0.19.1
jinja2                      3.1.4
joblib                      1.4.2
json5                       0.9.25
jsonpointer                 3.0.0
jsonschema                  4.23.0
jsonschema_specifications   NA
jupyter_events              0.10.0
jupyter_server              2.14.2
jupyterlab_server           2.27.3
kiwisolver                  1.4.5
lxml                        5.2.2
markupsafe                  2.1.5
matplotlib                  3.9.1
mpl_toolkits                NA
multidict                   6.0.5
multiprocess                0.70.16
natsort                     8.4.0
nbformat                    5.10.4
numcodecs                   0.13.0
numpy                       1.23.5
overrides                   NA
packaging                   24.1
parso                       0.8.4
platformdirs                4.2.2
prometheus_client           NA
prompt_toolkit              3.0.47
psutil                      6.0.0
pure_eval                   0.2.3
pyarrow                     17.0.0
pyarrow_hotfix              NA
pydev_ipython               NA
pydevconsole                NA
pydevd                      2.9.5
pydevd_file_utils           NA
pydevd_plugins              NA
pydevd_tracing              NA
pygments                    2.18.0
pyometiff                   1.0.0
pyparsing                   3.1.2
pythoncom                   NA
pythonjsonlogger            NA
pytz                        2024.1
pywin32_bootstrap           NA
pywin32_system32            NA
pywintypes                  NA
pywt                        1.6.0
referencing                 NA
requests                    2.32.3
rfc3339_validator           0.1.4
rfc3986_validator           0.1.1
rpds                        NA
scipy                       1.14.0
send2trash                  NA
six                         1.16.0
skimage                     0.19.2
sniffio                     1.3.1
stack_data                  0.6.3
tifffile                    2024.7.24
torch                       2.2.0+cpu
torchgen                    NA
tornado                     6.4.1
tqdm                        4.66.4
traitlets                   5.14.3
typing_extensions           NA
uri_template                NA
urllib3                     2.2.2
wcwidth                     0.2.13
webcolors                   24.6.0
websocket                   1.8.0
win32api                    NA
win32com                    NA
win32con                    NA
win32trace                  NA
winerror                    NA
xxhash                      NA
yaml                        6.0.1
yarl                        1.9.4
zarr                        2.18.2
zmq                         26.0.3
zstandard                   0.23.0
-----
IPython             8.26.0
jupyter_client      7.4.9
jupyter_core        5.7.2
jupyterlab          3.6.7
notebook            6.5.7
-----
Python 3.10.0 | packaged by conda-forge | (default, Nov 10 2021, 13:20:59) [MSC v.1916 64 bit (AMD64)]
Windows-10-10.0.17763-SP0
-----
Session information updated at 2024-08-08 18:03

**Comment by ngreenwald** [comment]
Hi @RouvenHoefflin, 
Is anything else different about the images? i.e. unsigned 16bit vs signed 32bit?

Can you take an image that previously worked, change the dtype, and confirm that the same image is no longer working?

Thanks,
Noah

**Comment by ofrag** [comment]
Hi Noah,

I work with Rouven on this, so I'll explain more on the situation. 
We use QuPath (with Cellpose) for cell segmentation and export the segmentation masks and channels for further processing with Nimbus.
When we work on a small sample where we have less than 65535 cells, QuPath exports the cell labels as unsigned 16bit image and processing with Nimbus works smoothly.  
When the sample has more than 65535 cells, QuPath (which is Java-based) opt for packing the cell labels as 24bit integer in an RGB image. 

We also wrote a utility Fiji script that convert the 24bit rgb image into 32bit float image. 
Both of these formats are not compatible with Nimbus (and lead to the above mentioned error). 

It would be beneficial if you can add support for any (or both) of these file formats. 
Nimbus seems to be a great tool, and we anticipate that many QuPath users would be happy to use it, and it would be nice if no further conversion is needed.  

Otherwise, can you please point us to the image format that should be used for cases where unsigned 16bit is not sufficient (>65535 cells)  

--------------------------------------
For the small dataset we validated that when we convert the 16bit label images (that works smoothly with Nimbus) into 32bit float images, we get the above error
--------------------------------------
The conversion from 24bit rgb values to actual cell label is as follows: 
Referring to the 3 channels of the rgb image as: RED, GREEN, BLUE:
label = RED*256*256 + GREEN*256 + BLUE

Thanks
Ofra

**Comment by ngreenwald** [comment]
Hey @ofrag, 
Can you guys try out the latest version and let us know if that solves your issue?

**Comment by ofrag** [comment]
Hi @ngreenwald 

segmentation masks in 32bit float format, works well.
Thanks a lot for the quick fix !
We can now continue testing Nimbus for our full dataset :-) 

segmentation masks in 24bit still give an error, 
for future version you may consider supporting also the 24bit segmentation mask format, so that QuPath users can avoid additional conversion

**Comment by JLrumberger** [comment]
Hi @ofrag,

I think the problem with the 24bit images stems from them being 3 channel images instead of single channel ones. I can add a function that handles 3 channel segmentation images, applies your conversion `label = RED * 256 * 256 + GREEN * 256 + BLUE` and posts a warning to the user to let him/her know that the images are handled internally. Do you think this would decrease friction for qupath users?

Best,
Lorenz

**Comment by ofrag** [comment]
Hi @JLrumberger 

I think this would be great !
It will save time, effort and disk space and will make the connection straightforward. 

We will be happy to share our code for saving QuPath segmentation results in Nimbus compatible format (channel-split together saving the masks)

best
Ofra

**Comment by JLrumberger** [comment]
Hi @ofrag,

we just updated the code, it should now allow segmentation maps saved as 3 channel float images and converts them with the formula you provided. Could you give it a try and let us know if everything works fine for you?

Best,
Lorenz

**Comment by ofrag** [comment]
Thanks @JLrumberger 

The QuPath output (for cases with cell number > 65535) is rgb image, which is 3 channel 8bit, and not 3 channel 32bit.
When using this output I get the error message below.
when using the converted (single channel) 32 bit it works fine.

I uploaded for you a small test dataset - single field of view, 5 channels, with both 32bit / 24bit rgb label masks. 
you can find it [here ](https://www.dropbox.com/scl/fo/z2xamsgpod106x1jf1hh5/AH0ynZoDLY4jprX-UEUuimM?rlkey=ednku1erjlu3r9wwvow1y07j5&st=e0edmyxs&dl=0)

`Available GPUs:  0
Predictions will be saved in ..\..\old_Nimbus-Inference\data\test_ofra\nimbus_output
Iterating through fovs will take a while...
Predicting ..\..\old_Nimbus-Inference\data\test_ofra\image_data\fov33...
  0%
 0/4 [00:00<?, ?it/s]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[11], line 1
----> 1 cell_table = nimbus.predict_fovs()

File D:\Ofra_Sync\GitHub\Nimbus-Inference\Nimbus-Inference\src\nimbus_inference\nimbus.py:234, in Nimbus.predict_fovs(self)
    232 print("Predictions will be saved in {}".format(self.output_dir))
    233 print("Iterating through fovs will take a while...")
--> 234 self.cell_table = predict_fovs(
    235     nimbus=self, dataset=self.dataset, output_dir=self.output_dir,
    236     normalization_dict=self.normalization_dict, save_predictions=self.save_predictions,
    237     half_resolution=self.half_resolution, batch_size=self.batch_size,
    238     test_time_augmentation=self.test_time_aug, suffix=self.dataset.suffix,
    239 )
    240 self.cell_table.to_csv(os.path.join(self.output_dir, "nimbus_cell_table.csv"), index=False)
    241 return self.cell_table

File D:\Ofra_Sync\GitHub\Nimbus-Inference\Nimbus-Inference\src\nimbus_inference\utils.py:387, in predict_fovs(nimbus, dataset, normalization_dict, output_dir, suffix, save_predictions, half_resolution, batch_size, test_time_augmentation)
    385 for channel_name in tqdm(dataset.channels):
    386     mplex_img = dataset.get_channel(fov, channel_name)
--> 387     input_data = prepare_input_data(mplex_img, instance_mask)
    388     if half_resolution:
    389         scale = 0.5

File D:\Ofra_Sync\GitHub\Nimbus-Inference\Nimbus-Inference\src\nimbus_inference\utils.py:286, in prepare_input_data(mplex_img, instance_mask)
    284 edge = find_boundaries(instance_mask, mode="inner").astype(np.uint8)
    285 binary_mask = np.logical_and(edge == 0, instance_mask > 0).astype(np.float32)
--> 286 input_data = np.stack([mplex_img, binary_mask], axis=0)[np.newaxis,...] # bhwc
    287 return input_data

File <__array_function__ internals>:180, in stack(*args, **kwargs)

File ~\.conda\envs\Nimbus\lib\site-packages\numpy\core\shape_base.py:426, in stack(arrays, axis, out)
    424 shapes = {arr.shape for arr in arrays}
    425 if len(shapes) != 1:
--> 426     raise ValueError('all input arrays must have the same shape')
    428 result_ndim = arrays[0].ndim + 1
    429 axis = normalize_axis_index(axis, result_ndim)

ValueError: all input arrays must have the same shape`

**Comment by JLrumberger** [comment]
Hi @ofrag,

thanks for your quick response and the example data. The problem was that the data was stored in channels-first format and my code expected channels last. I added support for both and already merged the changes. I ran inference on your data with the 24bit segmentation maps and everything seemed fine. Would you give it another try? Thanks so much for helping me with your feedback :)

Best,
Lorenz
